### ISSUE TITLE
Start-legion-watcher not running

### ISSUE THREAD

**Issue by cerahmed** [ldstein/legion-watcher#6]
Hey there, awesome tool that I couldn't yet test.

I have tried both downloading the .zip and cloning the repo into my machine (Legion 7 Gen 6 - Intel version), followed the Installation guide to run the script.

I started with running the setup-legion-watcher.bat - which worked and the GUI shows up.
Then tried running the start-legion-watcher.bat to get it running - but it fails with the following code:

`
Register-WMIEvent : Invalid class
At C:\Users\Ahmed\Desktop\Software\Legion Watcher\legion-watcher\lw.ps1:97 char:1 Register-WMIEvent 
    + CategoryInfo          : NotSpecified: (:) [Register-WmiEvent], ManagementException
    + FullyQualifiedErrorId : System.Management.ManagementException,Microsoft.PowerShell.Commands.RegisterWmiEventComm
   and
`

The error code stops there, though I suspect part of the error code is not showing.
I tried running as Admin with Unrestricted Policy, but nothing changed and I got the same error.

I also tried running the all_write_windows_log.ps1 and it throws an index error.

Appreciate your help.

![error](https://user-images.githubusercontent.com/21166481/156901078-5d3182c2-c5b4-48f8-84a3-ac21c305b5ec.png)

**Comment by ldstein** [comment]
Hi, 

Is Vantage installed? When you install Vantage, it adds WMI commands which are used by these scripts.

**Comment by cerahmed** [comment]
<img width="1034" alt="Screenshot 2022-03-08 114543" src="https://user-images.githubusercontent.com/21166481/157200511-6a9f537b-3ab3-4ef3-9e02-7d6e1a32fadb.png">


Yes it is. I reinstalled it from the Microsoft Store and from whatever link I found in Lenovo's website. Restarted the laptop and I still get the same error message.

Any idea on how I can troubleshoot it further?
Do you believe it has compatibility issue with Legion 7 Gen 6 Intel Version?

**Comment by ldstein** [comment]
Do you mind checking if the WMI Classes exist. In a new powershell terminal, enter:

`Get-WmiObject -Namespace "ROOT\WMI" -LIST | Where-Object {$_.name -match "LENOVO"}`

That should list all the Lenovo WMI classes which get installed with Vantage.

![image](https://user-images.githubusercontent.com/3657344/157208477-abbe7065-c273-43d7-b04f-5d085fd19804.png)

**Comment by cerahmed** [comment]
<img width="795" alt="events" src="https://user-images.githubusercontent.com/21166481/157213085-ef3b9433-0987-4b97-86c0-c7e8e69f5c19.png">

Events show correctly as yours.

It seems like running start-legion-watcher.bat fails only for the second event registration "LENOVO_GAMEZONE_POWER_CHARGE_MODE_EVENT_EVENT" at line 97 of lw.ps1 (as shown in the error screenshot of the OP).

Could there be a typo in the name of that event string? As I cannot see the full event name in PowerShell and I cannot verify.

**Comment by ldstein** [comment]
Interesting. You have a lot more Classes than I do. To view the full class names:
`Get-WmiObject -Namespace "ROOT\WMI" -LIST | Where-Object {$_.name -match "LENOVO"} | Write-Host` 

![image](https://user-images.githubusercontent.com/3657344/157216369-40c5612b-53cd-413c-bd18-89bf1063cd18.png)

**Comment by ldstein** [comment]
I wonder if there is indeed a typo in the classname of `LENOVO_GAMEZONE_POWER_CHARGE_MODE_EVENT_EVENT` in my version of Vantage which has been fixed in the version you're running.

Admittedly, it's been a long time since I upgraded.

**Comment by cerahmed** [comment]
<img width="870" alt="Screenshot 2022-03-08 143216" src="https://user-images.githubusercontent.com/21166481/157230383-21202718-4f15-4816-a8dd-ea014642cd1a.png">

Indeed, fixing the name of the second registration entry fixed the issue! However, how do I get the watcher to start? As it shows that they are not started.

**Comment by cerahmed** [comment]
<img width="947" alt="Screenshot 2022-03-09 100910" src="https://user-images.githubusercontent.com/21166481/157390472-52492d49-2a9d-41da-b156-dcbcde6a33a8.png">

I tried looking for either `Legion Watcher` or `LenovoVantageService` events in Event Viewer under `Windows Log -> Application` .. but neither seem to report any events.

**Comment by ldstein** [comment]
With Legion Watcher running, what happens if you press `FN+F9`?

Do you get any messages in the console?

![image](https://user-images.githubusercontent.com/3657344/157409022-444239df-d18b-4261-9182-51e55c7023d5.png)

**Comment by cerahmed** [comment]
<img width="849" alt="Screenshot 2022-03-09 100910" src="https://user-images.githubusercontent.com/21166481/157410566-ac307b52-2740-4bc5-be1c-ed6033f58d92.png">


I didn't know about that .. but checking now yes I do get a similar result.

What I'm trying to achieve is to listen for these events inside Event Viewer (using Task Scheduler) and perform a task accordingly. But still I don't see any event under Application related to Legion Watcher.

**Comment by ldstein** [comment]
Assuming it's working, they should appear in Windows Logs/Application:

![image](https://user-images.githubusercontent.com/3657344/157414456-efbe6a4b-68df-4af9-bb01-ede0403ee4a4.png)

**Comment by cerahmed** [comment]
Yes that is where I've been watching while initiating the events .. no logs appear there, even after they showed up inside `start-legion-watcher.bat` terminal.

Inside `setup-legion-watcher.bat` I ensured that the service is enabled at startup, but **any idea how to check if the service is actually running** (as I'm assuming the `start-legion-watcher.bat` is used for debugging only).

**Comment by ldstein** [comment]
In Task Manager, it will appear as a background process as a Powershell Script.

You could also modify the Task itself in Task Scheduler.

By default, it's running a VBS script which then launches Powershell. The only reason for this is to suppress the Powershell console.

If you modify the Task and launch Powershell directly, you can monitor what it is doing.

The command would be `powershell.exe` and arguments are ` -executionpolicy bypass -NoExit -nologo -nologo -file lw.ps1`

Original "hidden console" config:

![image](https://user-images.githubusercontent.com/3657344/157435714-38102aa2-2b92-4b5d-9abf-7c4dddcdff3f.png)

Visible Console hack:

![image](https://user-images.githubusercontent.com/3657344/157436195-9f67302a-1b55-458d-aeea-5c896b6c9ed7.png)

**Comment by ldstein** [comment]
An additional thought - are you running on battery?

I noticed the other day, when on battery, [Terminate iCue](https://github.com/ldstein/terminate-icue)'s scheduled task wouldn't run on startup. Maybe a battery saving thing, or an issue with the way I create the tasks. I'm planning to investigate it over the weekend.

**Comment by cerahmed** [comment]
<img width="882" alt="Screenshot 2022-03-09 150752" src="https://user-images.githubusercontent.com/21166481/157439306-c2a47473-7368-49a4-a175-b0dfbb28cc80.png">

In Task Scheduler I can see the task has never been run, and when I try to run it manually it doesn't .. I'll do some troubleshooting and see if I will make it run somehow.

Also, yes, I'm running on battery (actually on a 100W charger). I will try troubleshooting while plugging the original charger to see if that makes a difference!

**Comment by cerahmed** [comment]
So I got the script to work after changing to things in the Task properties:

1) Trigger: Changed it to `At Logon: Any User` - I previously had a similar issue where `At startup` does not seem to work in some cases.

<img width="473" alt="1" src="https://user-images.githubusercontent.com/21166481/157443279-40003c63-e868-41d7-9ef2-f5c2e7dda675.png">

2) Conditions: Unchecked `Run on AC Power` option.

<img width="484" alt="2" src="https://user-images.githubusercontent.com/21166481/157443292-926b4536-18b8-4461-bad9-0999a5a80a4f.png">

Now the script is running .. however, it seems like it's having difficulty writing the Event Log.
The powershell prompt shows that it's running `legion-watcher\scripts\all_write_windows_log.ps1` which is supposed to register the event, so my next guess is that there're some changes on the way `Write-EventLog` works.

<img width="860" alt="3" src="https://user-images.githubusercontent.com/21166481/157443311-e3332428-3e19-4223-822c-a29901d6b7f0.png">

**Comment by cerahmed** [comment]
Trying to register an Event Log manually similar to what `legion-watcher\scripts\all_write_windows_log.ps1` does  gives me the following error, which may be the reason why the event is not registered to the Event Viewer:

<img width="1280" alt="Screenshot 2022-03-09 160011" src="https://user-images.githubusercontent.com/21166481/157446666-b247f413-0088-4c11-8001-aef956f65e00.png">

**Comment by cerahmed** [comment]
![Screenshot 2022-03-09 192817](https://user-images.githubusercontent.com/21166481/157485628-be692496-91c2-41d1-8ce4-73baf617751b.png)

So finally I got it to work!

Turned out the `â€` I was getting is due a bad encoding of the `all_write_windows_log.ps1` file - perhaps after opening and sacing the .ps1 file in VSCode.

What worked for me was to:

1) Manually delete the faulty LogName created by the bad-encoded file using `Remove-LogName` command.
2) Reopen `all_write_windows_log.ps1` previously opened in VSCode, then resave it with **UTF-8 with BOM** encoding.
3) Restarted the Laptop and now it is logging!

From here I'll see the potential of automating tasks/RGB Lighting with the awesome utility!
Thanks a bunch for carrying on the conversation thus far, and I'll update the post should I run into problems.

**Comment by ldstein** [comment]
Nice one! That dash character is really strange. Could have been a result of copy pasting from some code pasted on the net. Weird how I didn't pick it up during my testing.

I made a few changes to address your findings:

- Added "run on battery" flag when creating the task
- Fixed the strangely encoded dashes in the monitor script
- Added checked for WMI classes before registering
- Added a watcher for `LENOVO_GAMEZONE_POWER_CHARGE_MODE_EVENT`

If you're willing to give master branch a try before I make a release, it would be greatly appreciated.

Thanks again for persisting with it, I think you're the second person who has stumbled across this project :)

**Comment by cerahmed** [comment]
I just came back to town and had a chance to test the master branch.
It's all working now perfectly! Thanks for the update.

By any means, do you know if it is possible for the Numlock key toggle to notify the Event Viewer when it's pressed (similar to how the FnLock functions)? I'm trying to achieve a keyboard lighting effect on FnLock (implemented) and Numlock (still looking).

**Comment by ldstein** [comment]
Great, thanks for the feedback.

Re: Numlock key toggle - you'll want a keylogger to achieve this and unfortunately out of scope of Legion Watcher (Legion Watcher only logs the special Lenovo hotkeys).

[Autohotkey](https://www.autohotkey.com) is one option - very suited to this type of activity.

Also seach for "keylogger howto" for other options (powershell, etc).

**Comment by cerahmed** [comment]
Thanks for the guidance, much appreciated.
